<script>
import CompanyCard from '~/components/CompanyCard'

export default {
  name: 'BoycottPage',
  components: {
    CompanyCard,
  },
}
</script>

<template>
  <section class="section">
    <div class="is-mobile">
      <CompanyCard
        title="Nestle"
        :reasons="[
          'https://en.wikipedia.org/wiki/Nestl%C3%A9#Baby_formula_marketing',
          'https://en.wikipedia.org/wiki/Nestl%C3%A9#Slavery_and_child_labour',
          'https://www.rfi.fr/en/zelensky-blasts-swiss-banks-nestle-over-business-as-usual-with-russia',
        ]"
        :subsidiaries="[
          'Carnation',
          'Enviga',
          'Nescau',
          'Ovaltine',
          'Supligen',
          'San Pellegrino',
          'Perrier',
          'Caro',
          'Nesquik',
          'Ricacao',
          'Sweet Leaf Tea',
          'Cocoa D\'Onofrio',
          'Libby\'s',
          'Nestea',
          'Romanette',
          'Peace Iced Tea',
          'Milo',
          'Special.T',
          'Blue Bottle Coffee Company',
          'Dolca',
          'Kirma',
          'Partner\'s Blend',
          'Starbucks',
          'Bonka',
          'Dolce Gusto',
          'Luomidis',
          'Ricoffy',
          'Sunrise',
          'Buondi',
          'Ecco',
          'Mountain Blend',
          'Ricoré',
          'Taster\'s Choice',
          'Chameleon Cold-Brew',
          'El Chaná',
          'Nescafé',
          'Ristretto',
          'Tofa',
          'Christina',
          'International Roast',
          'Nespresso',
          'Sical',
          'Zoégas',
          'Acqua Panna',
          'Ciego Montero',
          'Glaciar',
          'Nestlé Selda',
          'Santa Barbara',
          'Alaçam',
          'Contrex',
          'Henniez',
          'Nestlé Vera',
          'Santa Maria',
          'Aqua Mineral',
          'Cristalp',
          'Hépar',
          'Neuselters',
          'São Lourenço',
          'Aqua Pod',
          'Da Shan YunNan Spring',
          'Hidden Spring',
          'Pejo',
          'Sohat',
          'Aqua Spring',
          'Dar Natury',
          'Korpi',
          'Perrier',
          'Springs',
          'Aquarel',
          'Eco de los Andes',
          'La Vie',
          'Petrópolis',
          'Valvert',
          'Arctic',
          'Erikli',
          'Levissima',
          'Porvenir',
          'Viladrau',
          'Baraka',
          'Frische Brise',
          'Los Portales',
          'Prices Gate',
          'Vittel',
          'Buxton',
          'Gerber',
          'Minéré',
          'Recoaro',
          'Water Line',
          'Charmoise',
          'Ghadeer',
          'Nałęczowianka',
          'San Pellegrino',
          'Waterman',
          'Cerevita',
          'Cookie Crisp',
          'Gold Flakes',
          'Koko Krunch',
          'Shredded Wheat',
          'Cerelac',
          'Curiously Strawberry',
          'Golden Grahams',
          'Lion Cereal',
          'Shreddies',
          'Cheerios',
          'Curiously Cinnamon',
          'Milo cereals',
          'TRIO Cereal',
          'Chocapic',
          'Estralitas',
          'Golden Morn',
          'Nescau Cereal',
          'Uncle Tobys',
          'Cini Minis',
          'Fitness',
          'Golden Nuggets',
          'Nesquik Breakfast Cereal',
          'Clusters',
          'Force Flakes',
          'Honey Stars',
          'Nestlé Corn Flakes',
          'Chamyto',
          'Hirz',
          'Moça',
          'Ninho',
          'Yoco',
          'Chambino',
          'La Laitére',
          'Molica',
          'Ski',
          'Chandelle',
          'La Lechera',
          'Munch Bunch',
          'Sollys',
          'Chiquitin',
          'LC1',
          'Nestlé',
          'Sveltesse',
          'Club',
          'Le Viennois',
          'Nesvita',
          'Svelty',
          'Abuelita',
          'Chclait Chips',
          'Mabel\'s',
          'Nestlé Dessert',
          'Sahne Nuss',
          'Aero',
          'Cracker',
          'Nestlé Milk Chocolate',
          'Scorched Almonds',
          'After Eigth',
          'Choco Crossies',
          'Cremositas',
          'Nestlé with Almonds',
          'Sensação',
          'All Stars',
          'Chocolate Surpresa',
          'Gauchitas',
          'Nestlé Wonder Ball',
          'Smarties',
          'Allen\'s',
          'Chokito',
          'María Maizena',
          'Nestlé Yes',
          'Suflair',
          'Alpia',
          'Cocosette',
          'Moraditas',
          'Nuts',
          'Sublime',
          'Alpino',
          'Coffee Crisp',
          'Rosquitas',
          'Orion',
          'Sundy',
          'Animal Bar',
          'Crunch',
          'Salvado',
          'Passatempo',
          'Super 8',
          'D\'Onofrio',
          'TOP',
          'Peppermint Crisp',
          'Susy',
          'Bertie Beetle',
          'Dairy Box',
          'Wafer',
          'Perugina Baci',
          'Svitoch',
          'Besos de Moze',
          'Damak',
          'Yapita',
          'Plaistowe',
          'Szerencsi',
          'Big Turk',
          'Drifter',
          'Matchmakers',
          'Polo',
          'Tango',
          'Black Magic',
          'Fizzfindle',
          'Maverick',
          'Prestígio',
          'Tango Mini Galletas',
          'Blue Riband',
          'Frigor',
          'Mio',
          'Princessa',
          'Texan Bar',
          'Boci',
          'Galak/Milkybar',
          'Minties',
          'Quality Street',
          'Toffee Crisp',
          'Bono',
          'Garoto',
          'Mirage',
          'Rolo',
          'Tola',
          'Bon Pari',
          'Heaven',
          'Moça',
          'Rowntress',
          'Nestlé Toll House cookies',
          'Hercules Bars',
          'Munch',
          'Fruit Gums',
          'Trencito',
          'Breakaway',
          'Joe',
          'Munchies',
          'Fruit Pastilles',
          'Traingulo',
          'Callier',
          'Joff',
          'Negresco',
          'Jelly Tots',
          'Turtles',
          'Capri',
          'JOJO',
          'Negrita',
          'Juicy Jellies',
          'Walnut Whip',
          'Carlos V',
          'Lion',
          'Nestlé Candy Shop',
          'Randoms',
          'Yorkie',
          'charge',
          'Lollo',
          'Nestlé Classic',
          'Tooty Frooties',
          'Chips Ahoy!',
          'Chef Mate',
          'Davigel',
          'Minor\'s',
          'Santa Rica',
          'Buitoni',
          'Hälsans Kök',
          'Stouffer\'s',
          'California Pizza Kitchen',
          'Jack\'s Pizza',
          'Sweet Earth Foods',
          'Delissio Pizza',
          'Lean Cuisine',
          'Tombstone Pizza',
          'DiGiorno Pizza',
          'Lean Pockets',
          'Wagner Pizza',
          'Hot Pockets',
          'Papa Guiseppe',
          'Åhusglass',
          'Froneri',
          'Oreo Frozen Dessert Sandwiches',
          'Aino',
          'Häagen-Dazs',
          'Outshine',
          'Camy',
          'Kimo',
          'Pingviini',
          'D\'Onofrio',
          'Kimy',
          'Push-Up',
          'Делта',
          'Maxibon',
          'Real Dairy',
          'Δέλτα',
          'Mat Kool',
          'Savory',
          'Nestlé Dibs',
          'Mivvi',
          'Schöller',
          'Dreyer\'s',
          'Mövenpick',
          'Sorbetes',
          'Drumstick',
          'Nestlé Drumstick',
          'Temptations',
          'Eskimo',
          'Nestlé Ice Cream',
          'Underground is',
          'Frigor',
          'Nestlé Princessa',
          'zer0% Fat',
          'Frisco',
          'Boost',
          'Meritene',
          'Orgain',
          'Carnation Instant Breakfast',
          'Modulen',
          'Peptamen',
          'Compleat',
          'Atrium Innovations',
          'Persona Nutrition',
          'Crucial',
          'Douglas Laboratories',
          'Pure Encapsulations',
          'Diabetisource',
          'Genestra brands',
          'Resorb',
          'Fibersource',
          'Novasource Renal',
          'Resource',
          'Garden of Life',
          'Nutren',
          'Sustagen',
          'Glytrol',
          'Nuun',
          'Trophic',
          'Impact',
          'Optifast',
          'Vital Proteins',
          'Isosource',
          'Optifibre',
          'Wobenzym',
          'Alfare',
          'Guigoz',
          'Nestlé Bear Brand',
          'Beba',
          'Lactogen',
          'Bona',
          'Mindful Chef',
          'Nestogen',
          'Cerelac',
          'Nan',
          'Nestum',
          'Farinha Láctea',
          'NAN HA',
          'Nido',
          'FM 85',
          'NanSoy',
          'Piltti',
          'Freshly',
          'NaturNes',
          'PreNan',
          'Gerber',
          'Neslac',
          'SMA',
          'Good Start',
          'Nestlé',
          'Wyeth',
          'Neston',
          'Nesvita',
          'Pria',
          'Supligen',
          'Bakers',
          'Go Cat',
          'Supercoat',
          'Beta',
          'Gourmet',
          'Tails.com',
          'Bonio',
          'Lily\'s Kitchen',
          'Tidy Cats',
          'Bonnie',
          'Lucky Dog',
          'Totalcare',
          'Castor & Pollux',
          'Merrick',
          'Whole Earth Farms',
          'Chef Michael\'s Canine Creations',
          'Mon Petit',
          'Winalot',
          'Felix',
          'PetLife',
          'Fido',
          'Purina',
          'Buitoni',
          'Herta',
          'Katie\'s Pizza',
          'Toll House',
          'Carpathia',
          'CHEF.',
          'Haoji',
          'Maggi',
          'Thomy',
          'Totole',
          'Winiary',
          'Carnation',
          'Coffee-Mate',
          'Milo',
          'Nestlé Omega Plus',
          'Tendre Noix',
          'Acti-V',
          'Longa Vida',
          'Rawaytee Maza',
          'ActiPlus',
          'Molico',
          'Ski',
          'Fruit Selection Yogurt',
          'Munch Bunch',
          'Sweet N Tasty Yogurt',
          'Hirz',
          'Nestlé Raita',
          'Yello',
          'L\'Oreal',
          'Aberfoyle',
          'Arrowhead',
          'Calistoga',
          'Deep Spring',
          'Deer Park',
          'Ice Mountain',
          'Montclair',
          'Ozarka',
          'Powwow Water',
          'Pure Life/Pureza Vital/Via Pure',
          'Poland Spring',
          'Theodora',
          'Zephyrhills',
          'Plancoët',
          'Quézac',
          'Saint-Lambert',
          'Sainte-Alix',
          'Bit-O-Honey',
          'Wonder Ball',
        ]"
      />
      <CompanyCard
        title="Company"
        :reasons="['test', 'test2']"
        :subsidiaries="['sub1', 'sub2', 'sub3']"
      />
    </div>
  </section>
</template>